djangodemoproject/AppTwo/urls.py
from django.conf.urls import url
from AppTwo import views


urlpatterns = [
    url(r'^$',views.help,name= 'AppTwo'),
]

djangodemoproject/basicap/urls.py
from basicap import views
from django.conf.urls import url

#TEMPLATE URLS
app_name = 'basic_ap'

urlpatterns =[
    url(r'^register/$',views.register,name='register'),
    url(r'^login',views.user_login,name='user_login'),
]

djangodemoproject/djangodemoproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
#from AppTwo import views
# from basicforms import views
# from basicurlcoding import views
from basicap import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url('^logout/',views.user_logout,name='logout'),
    url('^special',views.special,name='special'),
    url(r'^basic_ap',include('basicap.urls')),
    # url(r'^basicurlcoding/', include('basicurlcoding.urls')),
    # url(r'^$',views.index,name = 'index2'),
    # url(r'^formpage',views.form_name_view),
    # url(r'^user/', include('first_app.urls')),
    # url(r'^help/', include('AppTwo.urls')),
    # url(r'^add_extension/', include('first_app.urls')),
]

djangodemoproject/basicap/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.name

djangodemoproject/basicap/forms.py
from django import forms

from  django.contrib.auth.models import User

from basicap.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

djangodemoproject/basicap/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basicap/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, NICE!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # user.set_password(user.password)
            # user.save()

            profile = profile_form.save(commit=False)
            profile.user = user  # ONE TO ONE RELATIONSHIP

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basicap/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("INVALID CREDENTIAL SUPPLIED")
    else:
        return render(request,'basicap/login.html',{})

djangodemoproject/templates/basicap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

</head>
<body>
<nav class="navbar sticky-top navbar-light bg-light">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class= "navbar-brand" href="{% url 'index' %}"> DJANGO </a></li>
            <li><a class= "navbar-brand" href="{% url 'admin:index' %}"> ADMIN</a></li>
            <li><a class= "navbar-brand" href="{% url 'basic_ap:register' %}">REGISTER </a></li>

            {% if user.is_authenticated %}
             <li><a class= "navbar-brand" href="{% url 'logout' %}">LOG OUT </a></li>
            {% else %}
             <li><a class= "navbar-brand" href="{% url 'basic_ap:user_login' %}">LOG IN </a></li>
            {% endif %}

        </ul>
    </div>
</nav>
{% block body_block %}
{% endblock %}
</body>
</html>

djangodemoproject/templates/basicap/index.html
<!DOCTYPE HTML>
{% extends "basicap/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1> Django USer Form Practice !!!</h1>
</div>

{% endblock %}

djangodemoproject/templates/basicap/login.html
<!DOCTYPE html>
{% extends 'basicap/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1> Please Login </h1>
    <form method="post" action="{% url 'basic_ap:user_login' %}">

        {% csrf_token %}
        <label for="username"> Username</label>
        <input type="text"  name = "username" placeholder="Enter Username">

        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
        </form>
</div>

{% endblock %}

djangodemoproject/templates/basicap/registration.html
<!DOCTYPE HTML>
{% extends 'basicap/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1> Thank you for registering </h1>
    {% else %}
    <h1> Register here </h1>
    <h3> Fill out the form </h3>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>



{% endblock %}