djangodemoproject/AppTwo/urls.py
from django.conf.urls import url
from AppTwo import views


urlpatterns = [
    url(r'^$',views.help,name= 'AppTwo'),
]

djangodemoproject/basicurlcoding/urls.py
from django.conf.urls import url
from basicurlcoding import views

# TEMPLATE TAGGING
app_name = 'basicurlcoding'

urlpatterns = [
    url(r'^relative/$', views.relative, name="relative"),
    url(r'^other/$', views.other, name="other"),
]

djangodemoproject/djangodemoproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
#from AppTwo import views
# from basicforms import views
# from basicurlcoding import views
from basicap import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url('^logout/',views.user_logout,name='logout'),
    url('^special',views.special,name='special'),
    url(r'^basic_ap',include('basicap.urls')),
    # url(r'^basicurlcoding/', include('basicurlcoding.urls')),
    # url(r'^$',views.index,name = 'index2'),
    # url(r'^formpage',views.form_name_view),
    # url(r'^user/', include('first_app.urls')),
    # url(r'^help/', include('AppTwo.urls')),
    # url(r'^add_extension/', include('first_app.urls')),
]

djangodemoproject/templates/basicurl/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-brand"><a href=#> BRAND</a></li>
                <li class="navbar-link" ><a href= "{% url 'admin:index' %}"> ADMIN</a></li>
                <li class="navbar-link" ><a href= "{% url 'basicurlcoding:other' %}" >OTHER</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Anything outside of it will be inherited of you extend -->
        {% endblock %}
    </div>
</body>
</html>

djangodemoproject/templates/basicurl/index.html
<!DOCTYPE html>
{% extends "basicurl/base.html" %}
{% block body_block %}

<h1> WELCOME TO INDEX </h1>
<h1> {{ text|cut:"0" }} </h1>
<h2> {{ num|add:99 }} </h2>
{% endblock %}

djangodemoproject/templates/basicurl/other.html
<!DOCTYPE html>

{% extends "basicurl/base.html" %}
    {% block bodyblock %}
    <H1>WELCOME TO OTHER</H1>
    <h3> This is an expample of template inheritance</h3>
{% endblock %}

djangodemoproject/templates/basicurl/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<H1> WELCOME TO RELATIVE URL TEMPLATES</H1>
<a href = "{% url 'basicurlcoding:other' %}" >The relative page</a>
<a href = "{% url 'admin:index' %}">Go to admin</a>
<a href = "{% url 'index' %}"> Go to Index </a>

</body>
</html>